### ISSUE TITLE
General repository and docker cleanup

### ISSUE THREAD

**Issue by Strazzom** [n1nj4sec/pupy#640]
It is good that @alxchk and @AlessandroZ have push privileges, but this repo is still a bit of a mess.

1) I propose that @alxchk move his repo to an unstable branch on this one, that way we can manage issues in one central location, rather than dividing them between two repos.

2) I also propose implementing a release system similar to Powershell Empire. All modifications should be made to the unstable branch, regression tested, and then merged into master. This will make my job easier, because I have been doing a lot of the regression testing, but it is hard to do so because there is no release system. If I know that there will be a release that will be "frozen" until the next one (a la Debian), then I can specifically do all tests on that one.

3) The docker image (https://hub.docker.com/r/alxchk/pupy/) is also less than optimal. Ideally, it should be under @n1nj4sec's name, that way there is no confusion about which docker repo is the official one. Failing that though, we should use @alxchk's existing repo, and all the old testing images should be removed. The master branch should be used to build the main image, and the "unstable" image (which is currently the only updated one) should be based on the unstable branch described above.

4) Another problem with the docker images is the build process. The way I am guessing it currently works is that the image is built from scratch each time. This is needlessly wasteful, because it does not make use of docker's layering system. As a result, each new pull is treated as en entirely new image. This is problematic, because that means I have to pull ~1.14GB of data each time I want to get the latest version. With other images, it only needs to pull the latest layers, rather than the full image.

One way to potentially solve the layering issue would be to build the base image once, and then have all subsequent builds simply pull the latest git commit. That is what many of us are doing manually anyway, so it makes sense. This way, all subsequent pulls do not waste bandwidth by trying to download the whole rebuilt image. This may be harder than I make it out to be, I am not a docker expert.

5) I also propose that someone review the issues on the main branch, as there are a lot of them that are backed up. Many are simple questions that have already been answered, and can therefore be closed. Out of the issues that are actually issues, we will need to test which are still broken in the latest version. If we can't reproduce them with the latest commit, I propose closing them.

6) We should only support a limited set of OSes. Debian (stable) and Kali Rolling seem logical to me, but we might also want to support Ubuntu as well. This is another idea taken from Empire, as they often received questions for relatively exotic OSes, which were simply out of scope for the project. Their solution to the problem of OS support was to have a docker container, something Pupy already does. If someone is not using a supported OS or the docker container, I propose simply refusing to fix it. This will simplify the project a lot. In regards to point 5, I propose closing any issues where they aren't using a supported OS, once we actually decide which ones to support.

EDIT: I have copied all wiki pages from the alxchk branch to the main one. I recommend deleting all alxchk wiki pages, so that there is only one wiki location.

**Comment by alxchk** [comment]
> I also propose implementing a release system similar to Powershell Empire. All modifications should be made to the unstable branch, regression tested, and then merged into master. This will make my job easier, because I have been doing a lot of the regression testing, but it is hard to do so because there is no release system. If I know that there will be a release that will be "frozen" until the next one (a la Debian), then I can specifically do all tests on that one.

This is surely best way to do something. The only issue to have manpower to do proper regression testing. We don't have any unit or integration tests, so this will be really painfull thing.  I pushed flake8 checker with huge ignore list. This should be starting point to stabilize.

> Another problem with the docker images is the build process. The way I am guessing it currently works is that the image is built from scratch each time.

Well, docker layers quite useless, so don't expect to reduce load size. The image will be different from the point where pupy copied to the system. This includes dev packages installed to build python deps and so on. If you have idea how to make this more efficient  - you can try.

> One way to potentially solve the layering issue would be to build the base image once, and then have all subsequent builds simply pull the latest git commit. That is what many of us are doing manually anyway, so it makes sense. This way, all subsequent pulls do not waste bandwidth by trying to download the whole rebuilt image. This may be harder than I make it out to be, I am not a docker expert.

The idea of this docker image to have clean system from some stateless point.

> This is problematic, because that means I have to pull ~1.14GB of data each time I want to get the latest version.

In case of active depelopment it's preferable to have non-docker deployment. Docker is more about fire-and-run

**Comment by Strazzom** [comment]
> Well, docker layers quite useless, so don't expect to reduce load size. The image will be different from the point where pupy copied to the system. This includes dev packages installed to build python deps and so on. If you have idea how to make this more efficient - you can try.

Yes, but even including deps, that is 330MB. If the pupy installation was on a different layer, then each new pull would only need to download that much. That saves you 2/3 of a gigabyte.

> The idea of this docker image to have clean system from some stateless point.

Yes. Having pupy on another layer doesn't change that. It just saves bandwidth.

> In case of active depelopment it's preferable to have non-docker deployment. Docker is more about fire-and-run

That would be great, but the Debian 9 installation process is still broken on my end. I have not tested it lately, but last I checked it was dysfunctional.

**Comment by alxchk** [comment]
> That would be great, but the Debian 9 installation process is still broken on my end. I have not tested it lately, but last I checked it was dysfunctional.

Right now it's also broken because of Lazagne dep

**Comment by AlessandroZ** [comment]
I have worked on lazagne last few weeks and I have removed lots of dependencies (pycrypto is not used anymore) and some more. I have clean the git repository (a git clone downloaded a file of 250 Mb and now it would be like 5 Mb). 
Everything has been pushed on my github repository, I didn't merge to pupy yet because, it's still in development but it's stable so if you need we can merge it (because I don't know when I will finish all I wanted to do on it).

**Comment by Strazzom** [comment]
In regards to the fourth point above (docker image layering):

I see that there was a recent commit [here](https://github.com/n1nj4sec/pupy/commit/91df054022358981b4b819be893b389e3152c420) which looks like it may have helped with this issue. I am going based on the title, I did not sufficiently understand the actual change to evaluate it properly.

**Comment by alxchk** [comment]
> I am going based on the title, I did not sufficiently understand the actual change to evaluate it properly.

This is just workaround for stupid pip+keyboard bugs, nothing more.

> Also, I think that we should officially support only Debian 9 and Kali. If @alxchk is in agreement, can I update the README and wiki to reflect this?

You can, why not. pupysh should work everywhere with python 2.7.15 and openssl 1.0 anyway..

**Comment by Strazzom** [comment]
Emphasis on _should._ I think that this will save some headache down the line.

**Comment by Strazzom** [comment]
I am going to close this issue, as all the original points are resolved.
